version: '3.8'
services:
  belajar-go-docker-service:
    build: .
    ports:
      - 8080:8000
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - mysql-service
  
  mysql-service:
    image: mysql:latest
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Haikal*18
      - MYSQL_HOST=mysql-1.cmaggkp0ghea.ap-southeast-1.rds.amazonaws.com
    ports:
      - 3306
    volumes:
      - ./mysqldb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - app-network

networks:
 app-network:
  driver: bridge